- name: Install Docker Compose
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: otherdevopsgene-ansible-ssm
    ansible_aws_ssm_region: us-east-2
  become: yes

  tasks:
  - name: Create docker config directory
    ansible.builtin.file:
      path: /home/ec2-user/.docker
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: '0755'

  - name: Create plugins directory
    ansible.builtin.file:
      path: /home/ec2-user/.docker/cli-plugins
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: '0755'

  - name: Download docker compose
    ansible.builtin.get_url:
      url: https://github.com/docker/compose/releases/download/v2.28.1/docker-compose-linux-x86_64
      dest: /home/ec2-user/.docker/cli-plugins/docker-compose
      checksum: sha256:https://github.com/docker/compose/releases/download/v2.28.1/docker-compose-linux-x86_64.sha256
      owner: ec2-user
      group: ec2-user
      mode: '0755'
    