---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: intro
  region: us-east-2

managedNodeGroups:
  - name: ng-intro
    instanceType: m5a.large
    minSize: 2
    maxSize: 5
    iam:
      withAddonPolicies:
        autoScaler: true

cloudWatch:
  clusterLogging:
    enableTypes: [all]
