- name: Install Java and Maven
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: otherdevopsgene-ansible-ssm
    ansible_aws_ssm_region: us-east-2
  become: yes

  roles:
    - role: geerlingguy.java
      java_packages:
        - java-21-amazon-corretto

    - role: gantsign.maven
    
