- name: Install k3s and kubectl
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: otherdevopsgene-ansible-ssm
    ansible_aws_ssm_region: us-east-2
  become: yes

  tasks:
  - name: Download k3s installation script
    ansible.builtin.get_url:
      url: https://get.k3s.io
      dest: /tmp/k3s-install.sh
      owner: ec2-user
      group: ec2-user
      mode: '0755'
  
  - name: Install k3s service
    ansible.builtin.command: 
      cmd: /tmp/k3s-install.sh --write-kubeconfig-mode "0644"
      creates: /etc/rancher/k3s/k3s.yaml

  - name: Install Checkov
    ansible.builtin.pip:
      name: checkov
    become_user: ec2-user

  - name: Install kubectl code completion
    ansible.builtin.shell:
      cmd: kubectl completion bash > /etc/profile.d/kubectl_completion.sh
      creates: /etc/profile.d/kubectl_completion.sh

  - name: git clone my-first-kubernetes
    ansible.builtin.git:
      repo: 'https://github.com/OtherDevOpsGene/my-first-kubernetes.git'
      dest: /home/ec2-user/environment/my-first-kubernetes
      version: main
    become_user: ec2-user
