- name: Surprise
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: otherdevopsgene-ansible-ssm
    ansible_aws_ssm_region: us-east-2
  become: yes

  tasks:
  - name: Never gonna give you up
    ansible.builtin.copy:
      src: rick.txt
      dest: /home/ec2-user/environment/surprise.txt
      owner: ec2-user
      group: ec2-user
      mode: '0644'
